/**
 * Migration plan & disk conversion.
 *
 * Turns the inventory into a concrete, per-VM runbook of Proxmox commands
 * (`qm create`, `qm importdisk`, `qm set`, VirtIO/TPM wiring…) and renders it
 * as a ready-to-review shell script. RDM/encrypted disks are flagged, not
 * silently converted.
 *
 * Part of V2P — VMware to Proxmox Migration Toolkit.
 * Crafted by SoyRage Agency — https://soyrage.es/
 * Licensed under the SoyRage Attribution License (see LICENSE).
 */

import { BRAND } from "../branding.js";
import type { Inventory, PlanStep, Vm } from "./types.js";

/** Placeholders the operator adjusts before running. */
const SRC_MOUNT = "/mnt/vmware-export"; // where the exported VMDKs live
const STORAGE = "local-lvm"; // target Proxmox storage
const ISO_STORE = "local"; // storage holding ISOs (virtio-win, etc.)

/** Proxmox guest names must be DNS-like; sanitise. */
function shellName(name: string): string {
  return name.replace(/[^a-zA-Z0-9.-]/g, "-").replace(/^-+|-+$/g, "") || "vm";
}

function ostype(vm: Vm): string {
  const os = vm.guestOs.toLowerCase();
  if (os.includes("windows 11")) return "win11";
  if (os.includes("windows")) return "win10";
  return "l26";
}

export function buildPlan(inv: Inventory): PlanStep[] {
  return inv.vms.map((vm, i) => {
    const vmid = 1000 + i;
    const uefi = vm.secureBoot || vm.vTpm;
    const commands: string[] = [];
    const notes: string[] = [];

    commands.push(
      `qm create ${vmid} --name ${shellName(vm.name)} --memory ${vm.memoryMb} --cores ${vm.cpu} ` +
        `--net0 virtio,bridge=vmbr0 --ostype ${ostype(vm)} --scsihw virtio-scsi-single` +
        (uefi ? ` --bios ovmf --efidisk0 ${STORAGE}:1,efitype=4m` : ""),
    );

    let scsiIndex = 0;
    vm.disks.forEach((d, di) => {
      if (d.rdm) {
        notes.push(`⚠ ${d.label} is an RDM — passthrough the LUN or migrate its data manually (not auto-converted).`);
        return;
      }
      const src = `${SRC_MOUNT}/${vm.name}/${vm.name}${di === 0 ? "" : "_" + di}.vmdk`;
      commands.push(`qm importdisk ${vmid} "${src}" ${STORAGE}   # ${d.label} (${d.sizeGb} GB)`);
      commands.push(`qm set ${vmid} --scsi${scsiIndex} ${STORAGE}:vm-${vmid}-disk-${scsiIndex},discard=on,ssd=1`);
      scsiIndex++;
    });

    commands.push(`qm set ${vmid} --boot order=scsi0`);

    if (/windows/i.test(vm.guestOs)) {
      commands.push(`qm set ${vmid} --ide2 ${ISO_STORE}:iso/virtio-win.iso,media=cdrom   # install VirtIO drivers on first boot`);
      notes.push("Install VirtIO storage & network drivers on first boot (virtio-win ISO attached).");
    }
    if (vm.vTpm) {
      commands.push(`qm set ${vmid} --tpmstate0 ${STORAGE}:1,version=v2.0`);
      notes.push("vTPM re-created. For BitLocker guests, have the recovery key ready.");
    }
    if (vm.encrypted) notes.push("⛔ VM is encrypted — decrypt in vSphere before exporting; disks were NOT queued for conversion.");
    if (vm.faultTolerance) notes.push("⛔ Turn off Fault Tolerance in vSphere first; use Proxmox HA + replication instead.");
    if (vm.snapshots > 0) notes.push(`Consolidate ${vm.snapshots} snapshot(s) before exporting.`);

    return { vm: vm.name, targetVmid: vmid, commands, notes };
  });
}

/** Render the whole plan as a reviewable bash script. */
export function renderScript(plan: PlanStep[], inv: Inventory): string {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    `# Migration runbook generated by ${BRAND.short} — ${BRAND.author} (${BRAND.url})`,
    `# Source: ${inv.vcenter} (${inv.vcenterVersion})`,
    "# REVIEW before running. Adjust the variables below to match your environment.",
    "set -euo pipefail",
    "",
    `SRC_MOUNT="${SRC_MOUNT}"   # where the exported VMDKs are mounted on the Proxmox node`,
    `STORAGE="${STORAGE}"       # target Proxmox storage for VM disks`,
    `ISO_STORE="${ISO_STORE}"   # storage that holds ISOs (virtio-win, etc.)`,
    "",
    "# Prerequisites: export/copy each VM's VMDK(s) to $SRC_MOUNT/<vm-name>/ (e.g. via ovftool,",
    "# scp from the ESXi datastore, or a shared NFS export). Then run this on the Proxmox node.",
    "",
  ];
  for (const step of plan) {
    lines.push(`# ─── ${step.vm}  →  VMID ${step.targetVmid} ───────────────────────────────`);
    for (const n of step.notes) lines.push(`#   ${n}`);
    for (const c of step.commands) lines.push(c);
    lines.push("");
  }
  lines.push(`echo "Done. Review each VM, then start it: qm start <vmid>"`);
  lines.push(`echo "Migration runbook by ${BRAND.author} — ${BRAND.url}"`);
  return lines.join("\n");
}
